import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Seed for consistency
np.random.seed(55)

# Generating 200 rows of data
n = 200
data = {
    'Transaction_ID': range(1001, 1001 + n),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], n),
    'Product_Type': np.random.choice(['Hardware', 'Software', 'Services'], n),
    'Units_Sold': np.random.randint(1, 15, n),
    'Unit_Price': np.random.uniform(50, 500, n),
    'Customer_Rating': np.random.uniform(1, 5, n),
    'Delivery_Time_Days': np.random.normal(5, 2, n)
}

df = pd.DataFrame(data)

# Calculate Revenue and add some outliers to Delivery Time
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df.loc[0:5, 'Delivery_Time_Days'] = 20  # Extreme delays

print("New dataset 'df' is ready!")
print(df)
print(df.shape)
print(df.columns)


# # Task 1: Regional Revenue (Aggregated Bar Plot)
# Goal: Compare the total revenue generated by each Region.
# Requirement: You must first group the data by 'Region' and sum the 'Total_Revenue'.
# Library: Use Matplotlib (plt.bar).

print("\nTask 1: Regional Revenue:- \n \t Create a bar chart showing Total Revenue by Region.\n \t Points to focus on: Group the data before plotting.\n\n")

# category = df.groupby('Region')['Total_Revenue'].sum()
# plt.bar(category.index,category,color='blue')
# plt.xlabel('Region')
# plt.ylabel('Total Revenue')
sns.barplot(x='Region',y='Total_Revenue',data=df)
plt.title('Total Revenue by Region')
plt.tight_layout()
plt.show()

# # Task 2: Rating vs. Delivery (Relationship Scatter)
# Goal: See if slow delivery times result in lower customer ratings.
# Requirement: Use 'Delivery_Time_Days' on X and 'Customer_Rating' on Y.
# Library: Use Seaborn (sns.scatterplot) and color the dots by 'Product_Type'.

print("\nTask 2: Rating vs. Delivery:- \n \t Plot Delivery Time vs Customer Rating.\n \t Points to focus on: Does a 20-day delivery have a low rating? Use hue='Product_Type'.\n\n")

sns.scatterplot(x='Delivery_Time_Days',y='Customer_Rating',data=df,hue='Product_Type')
plt.title('Delivery Time vs Customer Rating')
plt.tight_layout()
plt.show()

# # Task 3: Price Efficiency (Box Plot Outliers)
# Goal: Visualize the spread of 'Unit_Price' for each 'Product_Type'.
# Requirement: Identify if any Product Type has unusually expensive items (outliers).
# Library: Use Seaborn (sns.boxplot).

print("\nTask 3: Price Efficiency:- \n \t Show the price distribution for Hardware, Software, and Services.\n \t Points to focus on: Check the 'whiskers' and dots for outliers.\n\n")

sns.boxplot(x='Product_Type',y='Unit_Price',data=df)
plt.title('Product_Type vs Unit_Price')
plt.tight_layout()
plt.show()

# # Task 4: The Rating Wave (Histogram & KDE)
# Goal: Understand the common rating given by customers.
# Requirement: Create a histogram of 'Customer_Rating'.
# Library: Use Seaborn (sns.histplot) and set kde=True and bins=20.

print("\nTask 4: The Rating Wave:- \n \t Visualize the density of Customer Ratings.\n \t Points to focus on: Is the distribution 'Normal' (bell-shaped) or skewed?\n\n")

sns.histplot(x='Customer_Rating',data=df,hue="Product_Type",kde=True)
plt.title('Customer_Rating')
plt.tight_layout()
plt.show()

# # Task 5: The Full Matrix (Heatmap)
# Goal: Find which numerical variables move together.
# Requirement: Generate a correlation matrix and visualize it.
# Library: Use Seaborn (sns.heatmap) with annotations and the 'magma' color map.

print("\nTask 5: The Full Matrix:- \n \t Create a heatmap for all numeric columns in df_store.\n \t Points to focus on: Use annot=True and look for correlations between Units_Sold and Revenue.\n\n")

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="magma")
plt.tight_layout()
plt.show()